### ISSUE TITLE
忘記帳號

### ISSUE THREAD

**Issue by bluehomewu** [Shouheng88/LeafNote-Community#3]
剛剛重設了平板，忘記原先綁定的帳號
現在無法恢復高級版的功能

![Screenshot_20211229-033033_Gmail](https://user-images.githubusercontent.com/56945729/147600880-b91322da-fb92-4a9e-99f6-b819b3138b17.png)

這是我當時購買高級功能的 mail
不曉得是否可以用來協助我還原高級功能？

**Comment by Shouheng88** [comment]
晚点给你看下

**Comment by bluehomewu** [comment]
> 晚点给你看下

感謝！

**Comment by Shouheng88** [comment]
现在的账号体系需要你绑定一个邮箱账号，然后到自己的平板设置为 aux 设备，不过我打算后面重构下这个账号体系。你试下按照绑定账号的逻辑可以吗？

**Comment by bluehomewu** [comment]
> 现在的账号体系需要你绑定一个邮箱账号，然后到自己的平板设置为 aux 设备，不过我打算后面重构下这个账号体系。你试下按照绑定账号的逻辑可以吗？

AUX 設備？哪裡可以設定這個呢？
我現在不記得當時購買完後，是否有綁定帳號，也不確定綁定帳號所使用的 mail
因此我無法進行任何操作
目前有建立了一個新的帳號

**Comment by Shouheng88** [comment]
我查找了下，发现之前的设备没有绑定任何账号，但是订单信息确实存在的。
你可以这样处理，进入 关于 页面，长按 应用标题，此时会弹出一个对话框，把对话框里的信息发给我，我来帮你的设备提升为会员

**Comment by bluehomewu** [comment]
> 我查找了下，发现之前的设备没有绑定任何账号，但是订单信息确实存在的。 你可以这样处理，进入 关于 页面，长按 应用标题，此时会弹出一个对话框，把对话框里的信息发给我，我来帮你的设备提升为会员

Channel: google
Ver: 2.8.0
DevId: 21314(ANDROID_ID)
VipInfo: Not Vip
DeviceId: 0a93388c-f078-3a82-aad5-1aa5a1fb9cf0
DeviceType: ANDROID_TABLET
DeviceBound:true
UserId: 1109

**Comment by Shouheng88** [comment]
处理过了，请再试下

**Comment by bluehomewu** [comment]
> 处理过了，请再试下

![Screenshot_2021-12-31-12-57-11-653](https://user-images.githubusercontent.com/56945729/147804198-981a355a-eee1-412b-afca-390b59627e4b.jpeg)

還是一樣

**Comment by Shouheng88** [comment]
??杀进程重新进入应用也试过？

**Comment by bluehomewu** [comment]
> ??杀进程重新进入应用也试过？

對的，情況一樣

**Comment by Shouheng88** [comment]
我又检查了一下，发现没有问题。
你的用户设备列表是什么样呢？可能在列表里面设置一下

**Comment by bluehomewu** [comment]
> 我又检查了一下，发现没有问题。 你的用户设备列表是什么样呢？可能在列表里面设置一下

今天早上看，依舊是沒有啟用專業版的
現在回覆的時候，是已經啟用專業版的狀況了。

**Comment by Shouheng88** [comment]
现在可以了？之前设备网络有问题吗

**Comment by bluehomewu** [comment]
> 现在可以了？之前设备网络有问题吗

網路都沒有問題
