### ISSUE TITLE
語言顯示問題

### ISSUE THREAD

**Issue by bluehomewu** [Shouheng88/LeafNote-Community#4]
左側欄位中「雲同步」，顯示成「云同步」
在文件中，確實使用的是繁體的「雲」，而非簡體中文的「云」。
（手機使用的是免費版本）
![Screenshot_20220111-005838_言葉](https://user-images.githubusercontent.com/56945729/148806652-2f39859a-eedf-4af0-93be-07e16dc2218a.png)

**Comment by Shouheng88** [comment]
后面会修复这个词条的问题，谢谢🙏

**Comment by Shouheng88** [comment]
3.0 上面已修复，过几天发出来，谢谢
